### ISSUE TITLE
NaN value in Jones matrix

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/forward-model#53]
#### Description
When the volume shape in the axial dimension is 15 or larger, the forward projection of the estimated volume does not work.

#### Screenshots
![image](https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/23206511/7b02a52a-e82e-4f6a-879e-b6c293a9b817)

#### Files
- main_3d_reconstruction.py
- birefringence_implementations.py

#### To Reproduce
Start a reconstruction with the following non-default parameters:
- volume_shape = [15, 51, 51]
- ground truth volume: objects\GUVs\guv4_GT.h5
- initial estimated volume: objects\GUVs\guv4_GT.h5

**Comment by pvjosue** [comment]
Hey :) 
NAN is expected behavior, as the input and initial volume are the same, which is not a realistic scenario. 
The loss in the first iteration is 0, then when zero gets backpropagated, errors occur.
<img width="1251" alt="image" src="https://github.com/PolarizedLightFieldMicroscopy/forward-model/assets/1091910/6c57de9f-256d-4d32-b4b0-87b256e50ba6">

**Comment by pvjosue** [comment]
If you try with any other volume, no NaN should appear :)

**Comment by gschlafly** [comment]
Great, that makes sense, and also means the NaNs are an okay problem!
